language: python
python:
  - '3.6.5'

env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings_travis"
  - DJANGO_VERSION=2.2

services:
  - postgresql

script:
  - pip install -r pur_beurre/requirements.txt
  - python pur_beurre/manage.py test food/