language: python
python:
  - '3.6.5'

before_script:
  - pip install -r pur_beurre/requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings_travis"
  - DJANGO_VERSION=2.2

services:
  - postgresql

script:
  - python3 pur_beurre/manage.py test