language: python
python:
  - '3.6.5'

env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings_travis"

services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6

script:
  - pip install -r requirements.txt
  - python manage.py test