language: python
python:
  - '3.6.5'

env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings_travis"
  - DJANGO_VERSION=2.2

addons:
  postgresql: "11"
    apt:
      packages:
        -postgresql-11

services:
  - postgresql

script:
  - pip install -r requirements.txt
  - python manage.py test