# Generated by Django 2.2 on 2019-05-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='satured_fat_100g',
            new_name='saturated_fat_100g',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='satured_fat_level',
            new_name='saturated_fat_level',
        ),
    ]
